### ISSUE TITLE
formatting swallows leading zeros of integer literals

### ISSUE THREAD

**Issue by fkleedorfer** [atextor/turtle-formatter#35]
As stated in the [TTL spec](https://www.w3.org/TR/turtle/#abbrev), integer literals need to  match the regex '[+-]?[0-9]+', ie. there is nothing wrong, technically speaking, with leading zeros. As the formatter is not supposed to alter input data, it should reproduce leading zeros in the result.

It currently does not, and this leads to input and output model not being isomorphic if leading zeros are used.

The follwing test fails:
```
 @Test
    public void testIntegerLiteralWithLeadingZeros(){
        String content =   """
           @prefix : <http://example.com/ns#> .
           :thing :value 060.
           
           """;
        String expected = """
            @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
            @prefix : <http://example.com/ns#> .
            
            :thing :value 060 .""";
        final FormattingStyle style = FormattingStyle.DEFAULT;
        final TurtleFormatter formatter = new TurtleFormatter(style);
        final String result = formatter.applyToContent(content);
        assertThat(result.trim()).isEqualTo(expected);
    }
```

(The fact that the `xsd` prefix declaration is added is a fun extra bug not  being the issue right now.

**Comment by atextor** [comment]
Hi @fkleedorfer,
you are correct in what the spec allows as lexical values, and since leading zeroes do not carry semantics (as opposed to e.g. programming languages where the leading zero often indicates octal numbers), I'd consider using them bad style like wrong indentation or unnecessary use of `^^xsd:string`, which is why they're normalized by the formatter.
If the behavior of the formatter leads to input and output models not being isomorphic this is of course unacceptable, but how can this happen? I'd expect "60" and "060" to lead to the same parsed value, otherwise this is wrong behavior of the parser?

**Comment by fkleedorfer** [comment]
Yes, that is exactly the case. We had an integer field that is really a three-digit code, leading zeros are needed. I just changed the data, also concluding that it is a bad practice.  But, here is the old chestnut again, should the formatter make such decisions? Would it not be the job of an rdf linter? 

Am 2. Oktober 2024 19:35:46 MESZ schrieb Andreas Textor ***@***.***>:

**Comment by atextor** [comment]
I'd consider this a purely syntactical change, e.g., like changing
`:x :y "bla"^^xsd:string` to `:x :y "blah"` or `:x :y "true"^^xsd:boolean` to `:x :y true`. What do you think?

**Comment by fkleedorfer** [comment]
Well, `Model.isIsomorphicWith(Model)` returns `false` after this change.

**Comment by atextor** [comment]
This means that the lexical value is considered in the graph comparison in `isIsomorphicWith()` which I consider wrong. Nevertheless, I'm not dogmatic about this, thanks for taking the time to address this.
